
USE [master]
GO

/****** Object:  Database [Veterinary ]    Script Date: 12/2/2025 5:03:11 PM ******/
CREATE DATABASE [Veterinary ]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Veterinary', FILENAME = N'C:\Users\vlesl\Veterinary .mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Veterinary _log', FILENAME = N'C:\Users\vlesl\Veterinary _log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

ALTER DATABASE [Veterinary ] SET COMPATIBILITY_LEVEL = 150
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Veterinary ].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Veterinary ] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [Veterinary ] SET ANSI_NULLS OFF
GO

ALTER DATABASE [Veterinary ] SET ANSI_PADDING OFF
GO

ALTER DATABASE [Veterinary ] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [Veterinary ] SET ARITHABORT OFF
GO

ALTER DATABASE [Veterinary ] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [Veterinary ] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [Veterinary ] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [Veterinary ] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [Veterinary ] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [Veterinary ] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [Veterinary ] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [Veterinary ] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [Veterinary ] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [Veterinary ] SET  DISABLE_BROKER
GO

ALTER DATABASE [Veterinary ] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [Veterinary ] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [Veterinary ] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [Veterinary ] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [Veterinary ] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [Veterinary ] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [Veterinary ] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [Veterinary ] SET RECOVERY SIMPLE
GO

ALTER DATABASE [Veterinary ] SET  MULTI_USER
GO

ALTER DATABASE [Veterinary ] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [Veterinary ] SET DB_CHAINING OFF
GO

ALTER DATABASE [Veterinary ] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [Veterinary ] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO

ALTER DATABASE [Veterinary ] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [Veterinary ] SET ACCELERATED_DATABASE_RECOVERY = OFF
GO

ALTER DATABASE [Veterinary ] SET QUERY_STORE = OFF
GO

USE [Veterinary ]
GO

/****** Object:  Table [dbo].[Appointment]    Script Date: 12/2/2025 5:03:11 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Billing]    Script Date: 12/2/2025 5:03:11 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[MedicalRecord]    Script Date: 12/2/2025 5:03:11 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Pet]    Script Date: 12/2/2025 5:03:11 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[PetOwner]    Script Date: 12/2/2025 5:03:11 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[VeterinarianAdmin]    Script Date: 12/2/2025 5:03:11 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

USE [master]
GO

ALTER DATABASE [Veterinary ] SET  READ_WRITE
GO
